### ISSUE TITLE
Jobs - Fix jobs not showing

### ISSUE THREAD

**Issue by 9e-Docteur** [9e-Docteur/DocMod#21]
@Killarexe @Leaziurd I need help to finish my work, i don't have enough time to finish it, can you do it for me?
When opening Jobs menu (J key), jobs aren't showing.
Thanks for quick fix.

**Comment by onePlaceholder** [comment]
ClientJobsData.JOBS_LEVELS.getJobs() is empty...

**Comment by 9e-Docteur** [comment]
Strange, it should not

**Comment by 9e-Docteur** [comment]
Fixed by @Killarexe
