### ISSUE TITLE
Invalid Player Data

### ISSUE THREAD

**Issue by 9e-Docteur** [9e-Docteur/DocMod#22]
When joining a world. We get this error.

**Comment by Killarexe** [comment]
I don't have this bug on my local branch

**Comment by 9e-Docteur** [comment]
I'm gonna to try to make a new workspace wait

**Comment by 9e-Docteur** [comment]
I'm going to try tonight or tomorrow, i need to go

**Comment by Killarexe** [comment]
Ok

**Comment by 9e-Docteur** [comment]
Working, my workspace was weird because i was up to date. But i'm a bit rewritting the code now.
