### ISSUE TITLE
Garatim's Sonic Off does not have a name

### ISSUE THREAD

**Issue by 9e-Docteur** [9e-Docteur/DocMod#3]
![image](https://user-images.githubusercontent.com/74488745/197390962-cd51cc6a-7ce4-42d0-bae3-84898e2cd38d.png)

**Comment by Lera77** [comment]
![IMG_20240312_093533](https://github.com/9e-Docteur/DocMod/assets/163102641/16bdf809-25fb-45a8-81df-497efd396af1)

**Comment by 9e-Docteur** [comment]
Hello, i can't see your picture ;)
