### ISSUE TITLE
DocMod public server test issues list

### ISSUE THREAD

**Issue by Killarexe** [9e-Docteur/DocMod#7]
1. Albizia leaves are hard
2. Tree gen spawn each other
3. fix the advencements
4. missing loot tables for the chests in the dungeon
5. TODO add Albizia sapling (if possble)

**Comment by 9e-Docteur** [comment]
For the issue with the advencement, wich advencement?
Sapeling will be added

**Comment by 9e-Docteur** [comment]
Fixed
